language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: lBqE/SL6DtVLOCCb4vof6sX4Bri0qwR2pko4cibIYLBsbpIFnU+lvACKReJss/QzYJaIFq/1UmGHB40nP5oR62YdZrHN2jtd/cbX6RV79kOrqo09k8ukFaIRgqmr2274wScEZ92WQE7vgjbvaaGR2O8U+1cTH5Eq4pxwOERwT+1I5v/4esWlgS/Rf+7nSs7tUbZZKQoHDCJnK484Mo+9n556h3lTKfCscJV1ioV6E5swY1zNluNNOjr+SPomDtiyRaDnK/h6pS2yaf/axrEn5w6aES2Wvwb8O8A9ufqBztdvVqjJsRPrxgWZKwrjsuxDFVGCmzdQr1KIH4W0pZAum6GjamQk2O5n8vrIEa9D56K3ulQVzcz0mmdyVWO8A3RA2h289EnYl/+CG1KlOOeZntoolLL7rkqP24Jq4Wa1NSBkZ+1ULghVmZ8eaKntc3+swHSwRuFg3bu1V3bze+2DIxQT2aG76FsiQRtHz0c3muWMYmd8XK8yCF4VCgBC/jhVLeyQHB029fH+UHjeJF1uMmqO3wlueY0uxpn3uhDoHik0Gr2TQ4UCAEpcMP1i3MD8GjazLWxDqUNBHLXV+IyU4kIc0n2MKV4iKdjG75CYnrYdzfS3pwtnJUdvf7vd+g2Dgh+1o7mhRylZhK1D/jsT2KDx5FUI7+7sfaYFCBejsr4=
  app: noteful-rich-chasen
  on:
    repo: thinkful-ei22/w5d3_Richard_Chasen

    branch: feature/with-tests
