language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: "VxrOvHzyfqtj7DdgcQz5FYIVvDp7PdUIafiCcC16gmWL2hq7oDG4UKGdqZKVkjWhyExVgwvRoO5EbWvxdVJYoPAqUzdM2njCe5fFV3+ajwIYyZ+pKyCV0la2dzS/L81puMrCSi+RUhUwMKG3NVa43N7HNgISDZhVqAgsd0avfKGtXSf8RGEpm+6jqGNel86+dg7KumFmd62WJYhfgyf7zheo5YOUCCgrZ8vx74nYbHTVOnnO4lPNi4bqsqXTMOvUA8WEjLohzZQ2ecGINn+P00qFFXb5OfUIQQJpEPeRiT59+Of8gB9a7KoRyZkKbCk0Kb72aPH0X0Eg8BKGgC6rTtiRSPf8ejSzyXiAotdbpUNNXoP7aHikW0riIRSWbjvkZWteYTOUVrHEK5/G3bGcehxgJDTZPJl26koJRZHaGzMRHZsC/9+mcLn+Yt7ImvcDDrqO+OEln1Sdu6FD0FRBbyCbUb1JoEs1/wvWnlfbgwlJWI5CY7qv7q0ijoxwbz5g6NNLta5gfnOXoNeyaesbuTf0EeifhXrMQ5qGKUePJblWNm+g08xT+uReUK1mp9LirZYExQrDg3ZwcTBsI3pPmDwgAhyavOBfLf1dgE4vZCJoUwlY4SJ70oUAYqVuGv9G5hwmtEqbKClFoXiMwri2mUAx10BaS2sFuMQ/pGv8k7A="
  app: noteful-rich-chasen
  on:
    repo: thinkful-ei22/w5d3_Richard_Chasen
    branch: feature/with-tests
