language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: "fNpjVCyUEJTxRULheoSnynr/PYWcoVYNlzvkeKsMmt2hhCo9Uvg5be8wzPX7Nea8tt0kZ7v16qqDVvQSvwX6J9TXCF12thL1crW2KbclNr16Scxb309AiqqmddM2kX48Uihl41HmrIj63B1Z9gkQJsN0Ig6ZkcA1Qh07G1ceqXKqi/M/E6XmeLsUxoKUQTDLY0FZTJ5uzlVRLRe0CBMe/lfzSK/MPjBWZFIw7MyMcf7cBYk/SOqwCQS8E5gbwR22qsOOmRqWKlRo19rRy9fwp2Vlfd5LRxttddCIx9dXU9O1NmRJ0Q/dWFqIPZQNjXcjYyvT+/RkE25Xq7f4vRlltRSbzYTEcIpgbs1yXl5afkZWnLi7t7mGnhezQ2GMn/9EpcsoQb9cJksVjiBWYz+laTdOKV7nLqZXz/8nmCrwz1mRqHH7cS8iRbCOEYFaP0liM2bOInyNWEKvF3hHDkz/i67wessWzSXMWIBFqGsagPokpKHVobF1MyE7UtagFc9DfZ12U9qMRTYlApaZ525BojbzvKpVIZsQpSmPadUtHDXLM7k2HveRi31wCA4iiW1qvJi2H+eThzjH9joEJS3mP4Fe1SNDgbsSguoZTOKfFnreNOH2LaMedIiU3wFZEFbXb6lfhZmYCvdiR8e+0PTFDOcKoLnnGEJuK9djA555AUE="
  app: noteful-rich-chasen
  on:
    repo: thinkful-ei22/w5d3_Richard_Chasen
    branch: feature/with-tests
