language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: bRIcUK809EhC3qUEVCL3iFrmPSnjSTOKHHaZ2vXECKfNNxrxQFE5eXV/sCjSM+DKul7UgJMD01qfYGyu3xRjr9zHD1dQ1kRTZJwezXAZgLcXBqupM8LxqLg+/90NvQBA/WGMTPJyLGwdynQTN29VzFhjV2xME65qfIEQ+nvQdlbhQ5RLWAdd1xfJ1M1Woo6ct+q5RcREsmprBtMpLz6KdrvYl9jVCgjnYeI/5ez/1pYOrhuhneNRpMNsD6t4RiiuirG6x4AEljcZTKqMC2J6ynMLpAO11gf61W95x1cK4tcyPaFwPcoYTvqbwUdy/EckTheREuHXEicI4n1dRZhp+ey0VynIa9p+phtGqsMyDWh3I5y9X0zjyf2OUeT31ssmxrLt4sOVHhZVFQeuC6kOohSYW+S3/WNITXC3DdqJ3nmshUzlCKY6HoBtxmsJYWHt0ZwNzZLre14rU5KpF7KI6rSE+wpPRzofae6ePt03e75Hiax3zU+0IB72rQWHzDMT3/LEMU980HZv5lMcjLoO19oRrgS5YrDp1zRqBVJui/vRkC9nEsOwOM0j1WcDhoXCTAvJ6NkdqsKFzDkSUEYjDtc0Z+7Tg9CtXTvAe6w8KYTNsqCCIwqD1hAOoTqZgNWEiBVPm1T+Xw1SSpX0BhREw5Lu5UtUgKuM8/MpWIXNFDM=
  app: noteful-rich-chasen
  on:
    repo: thinkful-ei22/w5d3_Richard_Chasen
    branch: feature/with-tests
