language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: KrqnaD2hn5hqFPC+ESRmMjIj2PWr1b43EX5HOGFTlVB4y3/U8LuFNS9QaSq4tjwEV6kGH0hE0J4M3mgxsdbPp4Xq0nz6KQPV9GqBQ3N9D6bNp68ilRa/ILzZe1LFULAnAxB9AMfDVVsa5pENNClf5f2fi3ouidNb4casFncCIFds3Aixzjsx9IL0xzp/RrcjhWBcXX3pqU7hsXNu1WcWfhMx1t/7MFFFDTBuw9GqYukhFy6uJU1wlExK4u2Kk19fc08r5wDG1qTE6DVF/39guzCH9DiwYTzX3G63JpGEoTci4V/sZ9Ruo0gfWrGPqAh3t7x6ZsBhScWyHv4fopao+CZVXQdTRNngpCOuKtJj1L8TD89NPEMskRFrB8LIOCsSmB+e6BfjStXO9kPKbJJ9Jqn7qTEt+vipoGmAckhys8bKqPTzMg4Ep9dqFNVeYzdgtrSpRWPAO+1yb646Jq6PVFtTS+zULJxakOMdizrZEzgchL2+vrKsxBt4jAqN/eoNiqIJAKKqEXby87TFi3DXK0SRZ2vIlA48zmq8aln2RW3tpYRvj+UHdxEqObbFpcw3DvGMNQnU+CdhHf+Kf5dyAEqDsVRp8Jx2AFAIRqh6fmY1//EksUTT+S/fHCIEbZVFjXv7Ru+DNkqaF7PLLrZTMJ+PpVYgoZnHwuTRUxwwVHw=
  app: noteful-rich-chasen
  on:
    repo: thinkful-ei22/w5d3_Richard_Chasen
    branch: feature/with-tests

