language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: "HcFCLkq7ubYm1VHdwxfmMKFHOXy5irKqme7XFDuHWE+7F/BFHL/zDHIiKZx2epoc61ZH68t0sH7OBDJcfw+RDbep+5DY0qWE3e3ok8HBkKRgL6gVqhiX1PThlNKeSkTzoOhI/hN3/4B1y/IlpavWTvy5wddea1AAxHWJTt7NEJHOMQcLgSpaccT7ZccdBL9+NMYwOuOIIJ6EDIXxpM31tpOjatwXO3UdPUIDrQaZEOcTSWUJTGzja/7SKqMcMieKf45qi7bnjfFP0LbG9PeFXMxdkXkXP/g+GWimGg7pmAdBIpYDXiol8hnhCgzadEHz6ON6XBrknvoLBdJtZCVekMZwyId08KInb1h0eD5/ZNXtr9RKamBGI5zhpcbONFNeyDhkGKQ5k6Si8z4qkLmjWz63TeLsnPi5dLgovk8vLY3kvSmqTrLpqSUbYWXbjsC50imNan/zBVcLmcHZoTUJR4vPwAeuzKlNexqsXNPWRJXhEdz+eF7V+2eJilMudZexj0ukBJrfnA449uIAlu3IlCH/XVXzLVIN32WbMmWU+Xxg2pYGJNvEk/QowpnjrVmRrjtr3+cIb7x6VYE3J5ziAEmJYYaWbhRbsLRdY/q/0xKT2D5eardjo0FklKDQ+z8rkzMNLy34Gvy4S9BLcSKiLGzdjCC/LvjNwzTjZ8oPjco="
  app: noteful-rich-chasen
  on:
    repo: thinkful-ei22/w5d3_Richard_Chasen
    branch: feature/with-tests
