language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: JUAiizUIVQJVsQDa+TXW7bxcLHFocZGLjlCbobcXSPAHCUQeXpTUIc3xg2umz0F/pIPysoY1B4mEl5bXH6wTCDOgGY5VC3lhMladUdg6ZIZjwqnR0T9rU8OfWslqMRRDwUtB5LoMa3q24LbczyvuskxOnMIfpcSx05LXUzRqibkmLv6joNMk9TWRxPi4g2rmq5rIWmY4JWnTxrJ6iBY0y2IsM5Ypgsc49zB3bVI9RsVNAZl4lHq2aVCnvl37mXLFet48lxfOHazbpzEE/JhVVM1s7zzatz7FOI8P+WkcCc1wRVvChlKmXiolrAJIaFCdLisyjBBgdSv6B0FBUydN/ygbsi3QQ5UdCsVXVyf/qAWw+kckMJDa0SoD3FLAYgGG6td/NW9Qy9Q3f8FFbvME5VCu0m3DvByLu9aMYf1vN9yBUc4VeU+ErbE5sAa/tO17fP/fxe1ldZ2wOWEXqgySU0JDueYmhWymPWX3V373A8yPik3fBHsQFtV7vnAbs8aBnv9o3DFWPv4cykNc1KON2Bbl2fkcs/9r7XuE5bQ+UjlXBo2PQ8G4J9Or5P7ew5jS+g9j+V9c4p+uR0M4uJDRRXCf0LCIIcdv6Cpw1X31Rwy6wXG+UNEP7zA0pz6XKldyiIclvcK5dYLBCiRlA1mqNso24gKxLfQdV3gx6OEkxKU=
  app: noteful-rich-chasen
  on:
    repo: thinkful-ei22/w5d3_Richard_Chasen
    branch: feature/with-tests
 