language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: SRS9Iwghd9ib0/kNo9tUG6GoQ/cMUdJR/cYWRXcFcvB6RTQdOrip/iQ6kswbmJt4g9Isqhv2n4tI1HDZhrk03HZ6jcn2e8PavyQfXzNhzp2QsKKchpJBrYNgrrj0RtyUKdqk8quvc0Vvu0IGXP91kNAYexXIZseV+iNJ537zABmStL4QuUJeMUx1V9vBCNkbJtC9jt5klNHghxQ2TkscRYRL353aXc1mVZYR/DP86zmOSUBP0qIIuLj+MO3ZfSZeCo6RRijPGDu25f+yj9YyBMqcqdrrNUdTG4X7K1cGVpRdhJ6mP5aUzlk2f4DZ5PTPmxiU1N9z+toEFoGA73hSh2uaPW2awQlk4jSJB03zx2vTnLmcnrr6mXQtTPcrXonDY0I9bXj3OSZvV/MolTdyOuStL4oWVmzdCfmERfwWmxWNkrbu0riMENecgHQ927OSQebt9ibUyrxTEKAaX7WcOVNO2iZfW+irhYp+d5xeMnnAYFj7f0eRyrJnApMG5fwBtglxa6kaLim2hxljcLHMBPU3BoH/RF26fJw5s+w7zJ1+uqGtZQSepe+vjnmyK2/5vaxyPnmn99YJ0gwsTDz3RzZvq2AJdVr3qmO/ZhJukWdyqBiKSymdrgvMHmUjKEUGpkrt4Cr7F42ccBaiCdaPzSUaSN502oF9baRS/yXE76E=
  app: noteful-rich-chasen
  on:
    repo: thinkful-ei22/w5d3_Richard_Chasen
    branch: feature/with-tests
